# Generated by Django 4.0.1 on 2022-02-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='resolutions',
            field=models.CharField(max_length=100, null=True, verbose_name='video resolution'),
        ),
    ]
