# Generated by Django 4.0.2 on 2022-02-24 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_data_resolutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfile',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_files', to='stream.data'),
        ),
    ]
